server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/inventory/**

        - id: borrowing-service
          uri: lb://BORROWING-SERVICE
          predicates:
            - Path=/borrow/**

    loadbalancer:
      instances:
        INVENTORY-SERVICE:
          - uri: http://localhost:8081
          - uri: http://localhost:8083
        BORROWING-SERVICE:
          - uri: http://localhost:8082
